# -*- coding: utf-8 -*-
"""codecl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104wG_P6j9Xx-XgQrQOUumfFjqmNWHPHF
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install xgboost

import json
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
)
warnings.filterwarnings('ignore')
pd.set_option('display.float_format', '{:.4f}'.format)
print("Imports OK")

DATA_PATH = 'final_cleaned_data (2).xlsx'
df = pd.read_excel(DATA_PATH)

print(f"Shape : {df.shape}")
print(f"\nExercise distribution (TARGET):")
print(df['exercise'].value_counts())
print(f"\nSubjects : {sorted(df['subject_id'].unique())}")

# Class imbalance visualisation
fig, ax = plt.subplots(figsize=(10, 4))
counts = df['exercise'].value_counts()
colors = ['#E2703A' if c < 300 else '#378ADD' for c in counts.values]
ax.bar(counts.index, counts.values, color=colors)
ax.set_xlabel('Exercise')
ax.set_ylabel('Number of Reps')
ax.set_title('Sample Count per Exercise\n(Orange = minority classes)')
ax.tick_params(axis='x', rotation=30)
for i, v in enumerate(counts.values):
    ax.text(i, v + 10, str(v), ha='center', fontsize=10)
plt.tight_layout()
plt.savefig('exercise_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

IDENTIFIERS = ['rep_id', 'subject_id']
TARGET      = 'exercise'

# IMU — 100% null
IMU_COLS = [c for c in df.columns if c.startswith('imu_')]

# SLR — 93% null (only straight_leg_raise exercise)
SLR_COLS = ['left_knee_stability_slr','left_knee_min_during_slr',
            'right_knee_stability_slr','right_knee_min_during_slr']

DROP_ALL = list(set(IDENTIFIERS + [TARGET] + IMU_COLS + SLR_COLS))

groups = df['subject_id'].values

# Encode target
le_target = LabelEncoder()
y = le_target.fit_transform(df[TARGET].values)
class_names = le_target.classes_

print(f"Classes ({len(class_names)}): {list(class_names)}")
print(f"Encoded labels: {dict(zip(class_names, le_target.transform(class_names)))}")
print(f"\nDropped: {len(DROP_ALL)} cols")
print(f"  IMU (100% null): {len(IMU_COLS)}")
print(f"  SLR (93%  null): {len(SLR_COLS)}")

X_base = df.drop(columns=DROP_ALL).copy()
print(f"\nBase features: {X_base.shape[1]}")

def engineer_features(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()

    # ── A. Bilateral asymmetry ─────────────────────────────────────────────
    for joint in ['hip', 'knee', 'ankle']:
        l_rom, r_rom = X[f'left_{joint}_ROM'], X[f'right_{joint}_ROM']
        denom = ((l_rom + r_rom) / 2).replace(0, np.nan)
        X[f'fe_{joint}_ROM_asym']    = (l_rom - r_rom).abs() / denom
        l_vel, r_vel = X[f'left_{joint}_mean_velocity'], X[f'right_{joint}_mean_velocity']
        denom_v = ((l_vel + r_vel) / 2).replace(0, np.nan)
        X[f'fe_{joint}_vel_asym']    = (l_vel - r_vel).abs() / denom_v
        X[f'fe_{joint}_peak_asym']   = (X[f'left_{joint}_peak_angle'] - X[f'right_{joint}_peak_angle']).abs()
        X[f'fe_{joint}_smooth_diff'] = X[f'left_{joint}_smoothness']  - X[f'right_{joint}_smoothness']

    # ── B. Hip-knee kinematic chain ────────────────────────────────────────
    X['fe_left_hip_knee_ROM_ratio']  = X['left_hip_ROM']  / (X['left_knee_ROM']  + 1e-6)
    X['fe_right_hip_knee_ROM_ratio'] = X['right_hip_ROM'] / (X['right_knee_ROM'] + 1e-6)
    X['fe_hk_coupling_asym']         = X['left_hip_knee_coupling'] - X['right_hip_knee_coupling']

    # ── C. Knee flexion deficit ────────────────────────────────────────────
    X['fe_left_knee_flex_deficit']  = X['left_knee_start_angle']  - X['left_knee_peak_angle']
    X['fe_right_knee_flex_deficit'] = X['right_knee_start_angle'] - X['right_knee_peak_angle']
    X['fe_knee_flex_deficit_asym']  = X['fe_left_knee_flex_deficit'] - X['fe_right_knee_flex_deficit']

    # ── D. Ankle dorsiflexion ──────────────────────────────────────────────
    X['fe_ankle_dors_asym']    = (X['left_ankle_dorsiflexion'] - X['right_ankle_dorsiflexion']).abs()
    X['fe_ankle_ROM_combined'] = X['left_ankle_ROM'] + X['right_ankle_ROM']

    # ── E. Trunk lean ──────────────────────────────────────────────────────
    X['fe_trunk_lean_asym']  = (X['left_trunk_lean_proxy'] - X['right_trunk_lean_proxy']).abs()
    X['fe_trunk_lean_total'] = X['left_trunk_lean_proxy'] + X['right_trunk_lean_proxy']

    # ── F. Movement quality composite ─────────────────────────────────────
    for side in ['left', 'right']:
        for joint in ['hip', 'knee', 'ankle']:
            X[f'fe_{side}_{joint}_quality'] = X[f'{side}_{joint}_smoothness'] / (X[f'{side}_{joint}_EC_ratio'] + 1e-6)

    # ── G. Eccentric control ratio ─────────────────────────────────────────
    for side in ['left', 'right']:
        for joint in ['hip', 'knee']:
            desc = X[f'{side}_{joint}_mean_vel_desc']
            asc  = X[f'{side}_{joint}_mean_vel_asc']
            X[f'fe_{side}_{joint}_ecc_ratio'] = desc / (desc + asc + 1e-6)

    # ── H. Hesitation index ────────────────────────────────────────────────
    X['fe_left_total_hesitations']  = X['left_hip_hesitations']  + X['left_knee_hesitations']  + X['left_ankle_hesitations']
    X['fe_right_total_hesitations'] = X['right_hip_hesitations'] + X['right_knee_hesitations'] + X['right_ankle_hesitations']
    X['fe_hesitation_asym']         = X['fe_left_total_hesitations'] - X['fe_right_total_hesitations']

    # ── I. Temporal coordination lag ──────────────────────────────────────
    X['fe_total_temporal_lag'] = (
        X['hip_temporal_lag_fr'].abs() +
        X['knee_temporal_lag_fr'].abs() +
        X['ankle_temporal_lag_fr'].abs()
    )
    return X

X_eng = engineer_features(X_base)
fe_cols = [c for c in X_eng.columns if c.startswith('fe_')]
print(f"Engineered features added : {len(fe_cols)}")

null_cols = X_eng.columns[X_eng.isnull().any()].tolist()
print(f"Flagging & filling {len(null_cols)} exercise-specific null columns")
for col in null_cols:
    X_eng[f'{col}_missing'] = X_eng[col].isnull().astype(int)
    X_eng[col] = X_eng[col].fillna(0)

X = X_eng.copy()
assert X.isnull().sum().sum() == 0
print(f"Final feature matrix : {X.shape[0]} rows × {X.shape[1]} cols")
print("No nulls ✓")

from sklearn.utils.class_weight import compute_sample_weight

sample_weights = compute_sample_weight(class_weight='balanced', y=y)

print("Class weights applied:")
for cls_idx, cls_name in enumerate(class_names):
    w = sample_weights[y == cls_idx][0]
    n = (y == cls_idx).sum()
    print(f"  {cls_name:25s}  n={n:4d}  weight={w:.3f}")

model = XGBClassifier(
    n_estimators     = 300,
    max_depth        = 5,
    learning_rate    = 0.05,
    subsample        = 0.80,
    colsample_bytree = 0.70,
    min_child_weight = 5,
    gamma            = 1.0,
    reg_alpha        = 0.10,
    reg_lambda       = 1.0,
    objective        = 'multi:softprob',   # multiclass
    num_class        = len(class_names),
    eval_metric      = 'mlogloss',
    use_label_encoder= False,
    random_state     = 42,
    n_jobs           = -1,
)
print(model)
print(f"\nClasses: {len(class_names)}")

sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

fold_results = []
all_y_true, all_y_pred, all_y_proba = [], [], []

print("="*65)
print("  Exercise Classification — Subject-Aware 5-Fold CV")
print("="*65)

X_arr = X.values

for fold, (train_idx, test_idx) in enumerate(sgkf.split(X_arr, y, groups)):
    X_tr, X_te = X_arr[train_idx], X_arr[test_idx]
    y_tr, y_te = y[train_idx],     y[test_idx]
    sw_tr      = sample_weights[train_idx]
    test_subs  = sorted(np.unique(groups[test_idx]))

    model.fit(X_tr, y_tr,
              sample_weight=sw_tr,
              eval_set=[(X_te, y_te)],
              verbose=False)

    y_pred_fold  = model.predict(X_te)
    y_proba_fold = model.predict_proba(X_te)

    acc = accuracy_score(y_te, y_pred_fold)
    f1  = f1_score(y_te, y_pred_fold, average='macro')
    auc = roc_auc_score(y_te, y_proba_fold, multi_class='ovr', average='macro')

    fold_results.append({'fold': fold+1, 'acc': acc, 'f1_macro': f1,
                         'auc_macro': auc, 'test_subjects': test_subs})
    all_y_true.extend(y_te)
    all_y_pred.extend(y_pred_fold)
    all_y_proba.extend(y_proba_fold)

    print(f"  Fold {fold+1}  acc={acc:.4f}  f1={f1:.4f}  auc={auc:.4f}"
          f"  | test: {test_subs}")

all_y_true  = np.array(all_y_true)
all_y_pred  = np.array(all_y_pred)
all_y_proba = np.array(all_y_proba)

mean_acc = np.mean([r['acc']       for r in fold_results])
mean_f1  = np.mean([r['f1_macro']  for r in fold_results])
mean_auc = np.mean([r['auc_macro'] for r in fold_results])
std_acc  = np.std( [r['acc']       for r in fold_results])
std_f1   = np.std( [r['f1_macro']  for r in fold_results])
std_auc  = np.std( [r['auc_macro'] for r in fold_results])

print("="*55)
print(f"  Mean Accuracy  : {mean_acc:.4f}  ±{std_acc:.4f}")
print(f"  Mean F1 Macro  : {mean_f1:.4f}  ±{std_f1:.4f}")
print(f"  Mean AUC (OvR) : {mean_auc:.4f}  ±{std_auc:.4f}")
print("="*55)

print("\nClassification Report (all folds aggregated):")
print(classification_report(all_y_true, all_y_pred, target_names=class_names))

fold_df = pd.DataFrame(fold_results).set_index('fold')
display(fold_df[['acc','f1_macro','auc_macro']].style
        .highlight_max(color='#c6efce')
        .highlight_min(color='#ffc7ce')
        .format('{:.4f}'))



fi = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
top25 = fi.head(25)

fig, ax = plt.subplots(figsize=(10, 8))
colors = ['#E2703A' if n.startswith('fe_') else '#378ADD' for n in top25.index[::-1]]
ax.barh(range(len(top25)), top25.values[::-1], color=colors)
ax.set_yticks(range(len(top25)))
ax.set_yticklabels(top25.index[::-1], fontsize=9)
ax.set_xlabel('Importance Score')
ax.set_title('Top 25 Features\n(Orange = engineered, Blue = original)')
plt.tight_layout()
plt.savefig('exercise_feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()

fe_in_top = [f for f in top25.index if f.startswith('fe_')]
print(f"Engineered features in top 25: {len(fe_in_top)}")
print("\nTop 10:")
print(fi.head(10).to_string())



