# -*- coding: utf-8 -*-
"""FULL INTEGRATED 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1rqRf1sP2HPtaQu4ORWZFYCkf-Y8blk
"""

import sys, types
fake_audio = types.ModuleType('mediapipe.tasks.python.audio')
for sub in ['audio_classifier', 'audio_embedder', 'core']:
    fake_sub = types.ModuleType(sub)
    setattr(fake_audio, sub, fake_sub)
    sys.modules[f'mediapipe.tasks.python.audio.{sub}'] = fake_sub
sys.modules['mediapipe.tasks.python.audio'] = fake_audio
print('Monkey-patch applied')

import subprocess, sys
def pip(*args):
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', *args])

pip('mediapipe', 'protobuf==5.29.4', 'opencv-python-headless',
    'xgboost', 'shap', 'scipy', 'pyyaml', 'openpyxl',
    'torch', 'torchvision', 'scikit-learn', 'ipywidgets', 'pyserial')

import mediapipe as mp
print('mediapipe:', mp.__version__)
print('Install complete — restart runtime/kernel before running Cell 3')

import sys, types
fake_audio = types.ModuleType('mediapipe.tasks.python.audio')
for sub in ['audio_classifier', 'audio_embedder', 'core']:
    fake_sub = types.ModuleType(sub)
    setattr(fake_audio, sub, fake_sub)
    sys.modules[f'mediapipe.tasks.python.audio.{sub}'] = fake_sub
sys.modules['mediapipe.tasks.python.audio'] = fake_audio

import os, json, time, copy, pickle, urllib.request, logging
from datetime import datetime
from typing import List, Optional
from collections import Counter

import numpy as np
import pandas as pd
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from scipy.signal import savgol_filter, find_peaks
from scipy.interpolate import interp1d
from sklearn.metrics import accuracy_score, f1_score, classification_report
from scipy.stats import pearsonr

IN_COLAB = False
try:
    import google.colab
    IN_COLAB = True
    from google.colab import drive
    drive.mount('/content/drive')
    print('Running in Colab')
except ImportError:
    print('Running locally')

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')

if IN_COLAB:
    DATA_DIR   = '/content/drive/MyDrive/datasets'
    MODEL_SAVE = '/content/drive/MyDrive/models/rehabnet_best.pth'
else:
    DATA_DIR   = './datasets'
    MODEL_SAVE = './models/rehabnet_best.pth'

UIPRMD_CSV = os.path.join(DATA_DIR, 'uiprmd.csv')
KIMORE_CSV = os.path.join(DATA_DIR, 'squats_tabular_timeseries_binary.csv')
KERAAL_CSV = os.path.join(DATA_DIR, 'keraal_final_binary.csv')
os.makedirs(os.path.dirname(MODEL_SAVE), exist_ok=True)

TARGET_LEN  = 150
N_JOINTS    = 6
IN_CHANNELS = 3
MIN_FRAMES  = 20
FPS         = 30
N_EPOCHS    = 60
EPS         = 1e-6

JOINT_ORDER = ['l_hip', 'l_knee', 'l_ankle', 'r_hip', 'r_knee', 'r_ankle']

EXERCISE_LIST = [
    'deep_squat', 'hurdle_step', 'inline_lunge', 'side_lunge',
    'sit_to_stand', 'straight_leg_raise',
    'squat', 'ctk_squat', 'knee_bend', 'unknown'
]
EXERCISE2IDX = {e: i for i, e in enumerate(EXERCISE_LIST)}
N_EXERCISES  = len(EXERCISE_LIST)   # 10

HARDWARE_MODES = {
    0: {'name': 'assist', 'scale': -0.3, 'bias': 0.5, 'min': 0.0, 'max': 0.8},
    1: {'name': 'resist', 'scale':  0.6, 'bias': 0.1, 'min': 0.0, 'max': 0.8},
}
N_MODES = len(HARDWARE_MODES)

# Per-exercise min inter-peak distance (frames at ~25-30fps)
EX_MIN_DIST = {
    'inline_lunge': 100, 'side_lunge': 100,
    'deep_squat':    60, 'sit_to_stand': 80,
    'straight_leg_raise': 40,
    'knee_bend': 60, 'squat': 60, 'ctk_squat': 60,
    'hurdle_step': 45, 'unknown': 60, 'default': 60,
}

EX_MIN_ROM = {
    'inline_lunge': 35.0, 'side_lunge': 35.0,
    'deep_squat': 30.0, 'sit_to_stand': 35.0,
    'straight_leg_raise': 25.0,
    'knee_bend': 30.0, 'squat': 30.0, 'ctk_squat': 30.0,
    'hurdle_step': 20.0, 'unknown': 30.0, 'default': 30.0,
}

TARGET_ANGLES = {
    'deep_squat': 90., 'inline_lunge': 90., 'side_lunge': 90.,
    'sit_to_stand': 100., 'straight_leg_raise': 170.,
    'knee_bend': 90., 'squat': 90., 'default': 90.,
}

FEEDBACK_RULES = [
    # s[2]=l_peak/180  s[3]=r_peak/180
    # peak = the MINIMUM angle reached during the rep (i.e. maximum bend).
    # For a squat target of 90°: peak > 75° means the knee didn't bend deep enough.
    # We check the WORSE side (max of both peaks).
    {'name': 'insufficient_ROM',   'priority': 10,
     'check':   lambda s: max(s[2], s[3]) * 180 > 75,
     'message': 'Bend your knee a little further — try to reach 90°.',
     'short':   'Bend knee further'},
    # vel is now 95th-percentile of |frame-to-frame diff| × fps, /200.
    # A normal 3s squat at 25fps: ~1 deg/frame p95 → ~25 deg/s → 0.125 (fine).
    # A fast squat: ~3 deg/frame p95 → ~75 deg/s → 0.375 (above 0.40 threshold).
    {'name': 'too_fast',           'priority': 9,
     'check':   lambda s: s[5] * 200 > 80,
     'message': 'Slow down — take about 3 seconds for each bend.',
     'short':   'Move slower'},
    {'name': 'high_jerk',          'priority': 8,
     'check':   lambda s: s[6] * 10 > 8,
     'message': "Don't jerk your knee — keep the movement smooth.",
     'short':   'Avoid jerking'},
    {'name': 'trunk_compensation', 'priority': 7,
     'check':   lambda s: s[7] > 0.35,
     'message': 'Keep your back straight — try not to lean forward.',
     'short':   'Keep back straight'},
    # sym: |lr-rr|/mean(lr,rr)*100. >30% is clinically meaningful asymmetry.
    {'name': 'asymmetric',         'priority': 6,
     'check':   lambda s: s[4] * 100 > 30,
     'message': 'Try to put equal weight on both legs.',
     'short':   'Equal weight both legs'},
    {'name': 'temporal_lag',       'priority': 5,
     'check':   lambda s: s[8] * 150 > 15,
     'message': 'Keep both legs moving at the same time.',
     'short':   'Sync both legs'},
]

# ── Distribution alignment ───────────────────────────────
# These constants map the MediaPipe scalar distribution to the Vicon/dataset
# training distribution so the model sees in-distribution inputs.
#
# HOW TO UPDATE THESE:
#   Run Cell 9 (distribution diagnostic) on a known-good video + your
#   training data, then copy the printed means/stds here.
#
# CURRENT STATUS:
#   Values below are rough estimates — run Cell 9 to get real numbers
#   from your actual data before trusting classification results.
#
# SET SCALAR_ALIGN = False to disable alignment entirely (useful for debugging
# whether alignment is helping or hurting).
# SCALAR_ALIGN: set True only after running Cell 9 and updating the
# MP_MEAN/MP_STD/TRAIN_MEAN/TRAIN_STD constants from real data.
# With the current estimated constants, alignment crushes 'smooth' (z=487)
# and floors 'vel' (z=-2.6), corrupting 2 of 10 features.
# Leave False until Cell 9 has been run.
SCALAR_ALIGN = False

TRAIN_MEAN = np.array([0.349,0.500,0.631,0.475,0.670,
                        0.239,0.001,0.175,0.059,0.135], dtype=np.float32)
TRAIN_STD  = np.array([0.259,0.149,0.257,0.150,0.859,
                        0.165,0.001,0.108,0.171,0.214], dtype=np.float32)
MP_MEAN    = np.array([0.549,0.327,0.351,0.601,0.528,
                        0.804,0.013,0.002,0.133,0.006], dtype=np.float32)
MP_STD     = np.array([0.133,0.100,0.146,0.108,0.103,
                        0.251,0.008,0.002,0.327,0.002], dtype=np.float32)

MP_MODEL_PATH = '/tmp/pose_landmarker.task'
MP_MODEL_URL  = ('https://storage.googleapis.com/mediapipe-models/'
                 'pose_landmarker/pose_landmarker_heavy/float16/'
                 'latest/pose_landmarker_heavy.task')

print(f'Constants loaded. N_EXERCISES={N_EXERCISES}  N_MODES={N_MODES}')

# ── A. SHARED HELPERS ────────────────────────────────────

def safe_np(x, fill=0.0, clip=None, dtype=np.float32):
    x = np.asarray(x, dtype=dtype)
    x = np.nan_to_num(x, nan=fill, posinf=fill, neginf=fill)
    if clip is not None:
        x = np.clip(x, -clip, clip)
    return x.astype(dtype)

def valid_np(x):
    x = np.asarray(x)
    return x.size > 0 and np.isfinite(x).all()

def _smooth(arr, win=7, poly=2):
    arr = safe_np(arr)
    if len(arr) < win + 2:
        return arr
    w = win if win % 2 == 1 else win + 1
    w = max(w, poly + 2 if (poly + 2) % 2 == 1 else poly + 3)
    try:
        return safe_np(savgol_filter(arr, w, poly))
    except Exception:
        return arr

def _resample(arr, n):
    arr = safe_np(arr)
    if len(arr) == n:
        return arr
    if len(arr) < 2:
        return np.zeros(n, dtype=np.float32)
    return safe_np(np.interp(np.linspace(0,1,n), np.linspace(0,1,len(arr)), arr))

def _fill_missing(kps):
    kps = safe_np(kps)
    T, J, C = kps.shape
    for j in range(J):
        for c in range(C):
            col = kps[:, j, c]
            z   = (~np.isfinite(col)) | (col == 0.0)
            if z.all():
                opp = j + 3 if j < 3 else j - 3
                kps[:, j, c] = kps[:, opp, c]
            elif z.any() and (~z).sum() >= 2:
                f = interp1d(np.where(~z)[0], col[~z],
                             bounds_error=False, fill_value='extrapolate')
                kps[:, j, c] = f(np.arange(T))
    return safe_np(kps)

def _normalise_kps(kps):
    kps   = safe_np(kps)
    hip   = ((kps[:, 0, :] + kps[:, 3, :]) / 2.0).mean(axis=0)
    kps   = kps - hip
    l     = np.mean(np.linalg.norm(kps[:, 0, :] - kps[:, 2, :], axis=1))
    r     = np.mean(np.linalg.norm(kps[:, 3, :] - kps[:, 5, :], axis=1))
    scale = (l + r) / 2.0
    if not np.isfinite(scale) or scale < 1e-4:
        scale = 1.0
    return safe_np(np.clip(kps / scale, -5.0, 5.0), clip=5.0)

def build_adjacency():
    A = np.zeros((N_JOINTS, N_JOINTS), dtype=np.float32)
    for i, j in [(0,1),(1,2),(3,4),(4,5),(0,3),(1,4),(2,5)]:
        A[i,j] = A[j,i] = 1.0
    np.fill_diagonal(A, 1.0)
    d = np.diag(1.0 / np.sqrt(A.sum(axis=1) + EPS))
    return (d @ A @ d).astype(np.float32)

ADJ = build_adjacency()

# ── B. PS1 — VIDEO → DATAFRAME ───────────────────────────

MIN_DETECT_CONF = 0.5
MIN_TRACK_CONF  = 0.5

JOINT_COLS = []
for _jn in ['HipLeft','KneeLeft','AnkleLeft','HipRight','KneeRight','AnkleRight']:
    for _ax in ['x','y','z']:
        JOINT_COLS.append(f'{_jn}_{_ax}')
BASE_COLS = ['subject_id','session','label','frame_id','time_s','detection']

def ps1_prepare_frame(frame, target_w=640):
    h, w = frame.shape[:2]
    if w > target_w:
        frame = cv2.resize(frame, (target_w, int(h * target_w / w)))
    return frame

def ps1_extract_row(landmarks):
    mp_map = {
        'HipLeft': 23, 'KneeLeft': 25, 'AnkleLeft': 27,
        'HipRight': 24, 'KneeRight': 26, 'AnkleRight': 28,
    }
    row = {}
    for jname, idx in mp_map.items():
        lm = landmarks[idx]
        row[f'{jname}_x'] = float(lm.x)
        row[f'{jname}_y'] = float(lm.y)
        row[f'{jname}_z'] = float(lm.z)
    return row

def ps1_root_center(df):
    for ax in ['x','y','z']:
        mid = (df[f'HipLeft_{ax}'] + df[f'HipRight_{ax}']) / 2.0
        for jn in ['HipLeft','KneeLeft','AnkleLeft',
                   'HipRight','KneeRight','AnkleRight']:
            df[f'{jn}_{ax}'] = df[f'{jn}_{ax}'] - mid
    return df

# FIX: single 3D scale — preserves angles (old version used per-axis thigh)
def ps1_bone_normalize(df):
    for side, (h, k, a) in [
        ('L', ('HipLeft',  'KneeLeft',  'AnkleLeft')),
        ('R', ('HipRight', 'KneeRight', 'AnkleRight')),
    ]:
        leg_len = np.sqrt(
            (df[f'{h}_x'] - df[f'{a}_x'])**2 +
            (df[f'{h}_y'] - df[f'{a}_y'])**2 +
            (df[f'{h}_z'] - df[f'{a}_z'])**2
        ).mean() + 1e-6
        for jname in [h, k, a]:
            for ax in ['x','y','z']:
                df[f'{jname}_{ax}'] = df[f'{jname}_{ax}'] / leg_len
    return df

def _knee_angle_from_df(df, side='L'):
    prefix = {
        'L': ('HipLeft',  'KneeLeft',  'AnkleLeft'),
        'R': ('HipRight', 'KneeRight', 'AnkleRight'),
    }[side]
    h  = df[[f'{prefix[0]}_{ax}' for ax in 'xyz']].values
    k  = df[[f'{prefix[1]}_{ax}' for ax in 'xyz']].values
    a  = df[[f'{prefix[2]}_{ax}' for ax in 'xyz']].values
    v1, v2 = h - k, a - k
    cos = (np.sum(v1*v2, axis=1) /
           (np.linalg.norm(v1, axis=1) * np.linalg.norm(v2, axis=1) + EPS))
    return np.degrees(np.arccos(np.clip(cos, -1, 1)))

def ps1_extract_features(df):
    df['angle_knee_L']        = _knee_angle_from_df(df, 'L')
    df['angle_knee_R']        = _knee_angle_from_df(df, 'R')
    df['angle_knee_L_smooth'] = _smooth(df['angle_knee_L'].values)
    df['angle_knee_R_smooth'] = _smooth(df['angle_knee_R'].values)
    return df

def ps1_clean_nulls(df):
    return df.ffill().bfill().fillna(0.0)

def _ensure_mp_model():
    if not os.path.exists(MP_MODEL_PATH):
        print('  Downloading MediaPipe pose model (~30 MB)...')
        urllib.request.urlretrieve(MP_MODEL_URL, MP_MODEL_PATH)
        print('  Downloaded.')

def ps1_process_video(video_path, patient_id,
                      exercise='unknown', session='1', label='unknown'):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f'Cannot open video: {video_path}')

    fps_vid = cap.get(cv2.CAP_PROP_FPS) or FPS
    rows, frame_idx, detected = [], 0, 0
    t0 = time.time()

    _ensure_mp_model()
    import mediapipe as mp
    from mediapipe.tasks import python as _mptasks
    from mediapipe.tasks.python import vision as _mpvision

    opts = _mpvision.PoseLandmarkerOptions(
        base_options=_mptasks.BaseOptions(model_asset_path=MP_MODEL_PATH),
        running_mode=_mpvision.RunningMode.VIDEO,
        num_poses=1,
        min_pose_detection_confidence=MIN_DETECT_CONF,
        min_pose_presence_confidence=MIN_DETECT_CONF,
        min_tracking_confidence=MIN_TRACK_CONF,
        output_segmentation_masks=False,
    )
    frame_step_ms = int(1000.0 / fps_vid)

    with _mpvision.PoseLandmarker.create_from_options(opts) as pose:
        while True:
            ok, frame = cap.read()
            if not ok:
                break
            frame_idx += 1
            frame_ms   = frame_idx * frame_step_ms
            prepped    = ps1_prepare_frame(frame)
            rgb        = cv2.cvtColor(prepped, cv2.COLOR_BGR2RGB)
            mp_img     = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
            res        = pose.detect_for_video(mp_img, frame_ms)

            row = {'subject_id': patient_id, 'session': session,
                   'label': label, 'frame_id': frame_idx,
                   'time_s': round(frame_idx / fps_vid, 4), 'detection': 0}
            row.update({col: float('nan') for col in JOINT_COLS})
            if res.pose_landmarks and len(res.pose_landmarks) > 0:
                detected += 1
                row['detection'] = 1
                row.update(ps1_extract_row(res.pose_landmarks[0]))
            rows.append(row)

    cap.release()
    if frame_idx == 0:
        raise ValueError('Video is empty')

    det_pct = 100 * detected / frame_idx
    print(f'  PS1: {frame_idx} frames  fps={fps_vid:.0f}  '
          f'detection={det_pct:.0f}%  {time.time()-t0:.1f}s')

    df = pd.DataFrame(rows, columns=BASE_COLS + JOINT_COLS)
    df = df[df['detection'] == 1].reset_index(drop=True)
    df = ps1_root_center(df)
    df = ps1_bone_normalize(df)   # fixed version — 3D scale
    df = ps1_extract_features(df)
    df = ps1_clean_nulls(df)
    df.attrs['fps'] = fps_vid     # store fps for downstream use
    return df

# ── C. KEYPOINT PROCESSING ───────────────────────────────

def process_keypoints(raw):
    raw = safe_np(raw)
    if raw.ndim != 3 or raw.shape[1] != N_JOINTS or raw.shape[2] != 3:
        raise ValueError(f'Expected (T,{N_JOINTS},3), got {raw.shape}')
    if len(raw) < MIN_FRAMES:
        raise ValueError(f'Too short: {len(raw)} frames')
    for j in range(N_JOINTS):
        for c in range(3):
            raw[:, j, c] = _smooth(raw[:, j, c])
    raw = _fill_missing(raw)
    out = np.zeros((TARGET_LEN, N_JOINTS, 3), dtype=np.float32)
    for j in range(N_JOINTS):
        for c in range(3):
            out[:, j, c] = _resample(raw[:, j, c], TARGET_LEN)
    return safe_np(_normalise_kps(out), clip=5.0)

# FIX: axis=1 (L2 norm per frame) not 1 as L1 norm
# FIX: jerk from angle signal not raw coords
# FIX: extra smooth before velocity/jerk to suppress MediaPipe jitter
# FIX: accept fps parameter so velocity is correct for any video framerate
def extract_scalars(kps, fps=None):
    if fps is None:
        fps = FPS   # default 30; override with actual video fps when available
    kps = safe_np(kps, clip=5.0)

    def _ang(a, b, c):
        ba, bc = a - b, c - b
        d = np.maximum(
            np.linalg.norm(ba, axis=1) * np.linalg.norm(bc, axis=1), EPS
        )
        return np.degrees(np.arccos(np.clip(np.sum(ba*bc, axis=1) / d, -1, 1)))

    def _sg(arr):
        w = min(11, len(arr) - 1 if len(arr) % 2 == 0 else len(arr))
        w = max(w if w % 2 == 1 else w - 1, 5)
        try:    return savgol_filter(arr, w, 2)
        except: return arr

    lk   = _ang(kps[:,0,:], kps[:,1,:], kps[:,2,:])
    rk   = _ang(kps[:,3,:], kps[:,4,:], kps[:,5,:])
    lk_s = _sg(lk)
    rk_s = _sg(rk)

    lr  = float(np.nanmax(lk) - np.nanmin(lk))
    rr  = float(np.nanmax(rk) - np.nanmin(rk))
    sym = abs(lr-rr) / ((lr+rr)/2 + EPS) * 100 if (lr+rr) > 1 else 0.0

    # Velocity: 95th-percentile of |frame-to-frame angle change| × fps
    # Using max() picks up single jitter spikes and fires on normal squats.
    # 95th-percentile is robust to 1–2 noisy frames while still catching
    # genuinely fast movement.
    if len(lk_s) > 1:
        diffs = np.abs(np.diff(lk_s))
        vel   = float(np.percentile(diffs, 95) * fps)
    else:
        vel = 0.0

    # Jerk from angle signal (not raw coords — too small after normalisation)
    acc  = np.gradient(np.gradient(lk_s))
    jerk = float(np.nanmean(np.abs(np.gradient(acc))))

    hip   = (kps[:,0,:] + kps[:,3,:]) / 2.0
    pk    = int(np.argmin(lk))
    trunk = float(abs(hip[pk, 0] - hip[0, 0]))

    lkc, rkc = lk_s - np.nanmean(lk_s), rk_s - np.nanmean(rk_s)
    lag = float(abs(
        np.argmax(np.correlate(lkc, rkc, 'full')) - (len(lk_s) - 1)
    )) if np.nanstd(lkc) > EPS and np.nanstd(rkc) > EPS else 0.0

    # Smoothness: ratio of frame-to-frame std to movement range.
    # Near 0 = jerky (std ~ range), near 1 = smooth (std << range).
    # Robust across different exercises and normalisation scales.
    range_proxy = (lr + rr) / 2.0 + EPS
    smooth = float(np.clip(1.0 - np.nanstd(np.diff(lk_s)) / range_proxy, 0, 1))

    return safe_np(np.array([
        np.clip(lr / 180,         0, 1),
        np.clip(rr / 180,         0, 1),
        np.clip(np.min(lk) / 180, 0, 1),
        np.clip(np.min(rk) / 180, 0, 1),
        np.clip(sym / 100,        0, 5),
        np.clip(vel / 200,        0, 5),
        np.clip(jerk / 10,        0, 5),
        np.clip(trunk,            0, 5),
        np.clip(lag / TARGET_LEN, 0, 1),
        smooth,
    ], dtype=np.float32), fill=0.0, clip=10.0)

# Distribution alignment: maps MediaPipe scalars to Vicon training distribution
def align_scalars(sc):
    if not SCALAR_ALIGN:
        return sc.copy()
    mp_std_safe = np.where(MP_STD < 1e-6, 1.0, MP_STD)
    z = (sc - MP_MEAN) / mp_std_safe
    # Guard: clip z to ±3 before mapping. Without this, a single bad constant
    # (e.g. MP_STD[9]=0.002 when smooth is now 0.98) causes z=487 → clipped
    # to 5.0 → the feature is destroyed for every rep.
    z = np.clip(z, -3.0, 3.0)
    return np.clip(z * TRAIN_STD + TRAIN_MEAN, 0.0, 5.0).astype(np.float32)

# ── D. BRIDGE ────────────────────────────────────────────

def _df_to_kps(df):
    cols = []
    for jn in ['HipLeft','KneeLeft','AnkleLeft',
               'HipRight','KneeRight','AnkleRight']:
        cols += [f'{jn}_x', f'{jn}_y', f'{jn}_z']
    return df[cols].values.astype(np.float32).reshape(len(df), N_JOINTS, 3)

def _segment_reps(df, angle_col='angle_knee_L_smooth',
                  min_frames=MIN_FRAMES, min_rom=None, exercise='unknown'):
    if angle_col in df.columns:
        angles_l = df[angle_col].ffill().bfill().values
    else:
        angles_l = _knee_angle_from_df(df, 'L')

    try:
        angles_r = _knee_angle_from_df(df, 'R')
    except Exception:
        angles_r = angles_l

    angles_l = np.asarray(angles_l, dtype=np.float32)
    angles_r = np.asarray(angles_r, dtype=np.float32)
    n = len(angles_l)

    if n < min_frames:
        print(f'  Segmenter: too short n_frames={n}')
        return []

    ex_key   = exercise if exercise in EX_MIN_DIST else 'default'
    min_dist = max(EX_MIN_DIST[ex_key], n // 20)
    min_rom  = EX_MIN_ROM.get(ex_key, EX_MIN_ROM['default']) if min_rom is None else min_rom

    rom_l = float(np.nanmax(angles_l) - np.nanmin(angles_l))
    rom_r = float(np.nanmax(angles_r) - np.nanmin(angles_r))
    rom   = max(rom_l, rom_r)

    if rom < min_rom:
        print(f'  Segmenter: exercise={exercise}  n={n}  '
              f'ROM_L={rom_l:.1f}  ROM_R={rom_r:.1f}  NO VALID MOVEMENT')
        return []

    angles = angles_l if rom_l >= rom_r else angles_r

    peaks, _ = find_peaks(
        -angles,
        distance=min_dist,
        prominence=max(12.0, min_rom * 0.6),
        width=max(5, min_dist // 5),
    )

    print(f'  Segmenter: exercise={exercise}  n={n}  min_dist={min_dist}  '
          f'ROM_L={rom_l:.1f}  ROM_R={rom_r:.1f}  peaks={len(peaks)}')

    if len(peaks) == 0:
        return []

    mids   = [(peaks[i]+peaks[i+1])//2 for i in range(len(peaks)-1)]
    bounds = [0] + mids + [n]
    reps   = []
    for i in range(len(bounds)-1):
        rep = df.iloc[bounds[i]:bounds[i+1]].copy()
        if len(rep) < min_frames:
            continue
        try:
            rep_rom = max(
                float(np.nanmax(_knee_angle_from_df(rep,'L')) -
                      np.nanmin(_knee_angle_from_df(rep,'L'))),
                float(np.nanmax(_knee_angle_from_df(rep,'R')) -
                      np.nanmin(_knee_angle_from_df(rep,'R'))),
            )
        except Exception:
            rep_rom = rom
        if rep_rom >= min_rom:
            reps.append(rep)
        else:
            print(f'    reject rep {i+1}: ROM={rep_rom:.1f} < {min_rom:.1f}')
    return reps

def ps1_df_to_samples(df, patient_id, exercise='unknown',
                       label=-1, source='patient_video'):
    reps   = _segment_reps(df, exercise=exercise)
    ex_idx = EXERCISE2IDX.get(exercise, EXERCISE2IDX['unknown'])
    fps    = df.attrs.get('fps', FPS)   # use actual video fps for velocity
    print(f'  Bridge: {len(reps)} rep segments → ', end='')
    samples = []
    for i, rep_df in enumerate(reps):
        try:
            kps = _df_to_kps(rep_df)
            kps = process_keypoints(kps)
            sc  = extract_scalars(kps, fps=fps)
            samples.append({
                'keypoints':    kps,
                'adj':          ADJ,
                'scalars':      sc,
                'label':        max(label, 0),
                'quality':      float(max(label, 0)),
                'exercise':     exercise,
                'exercise_idx': ex_idx,
                'subject':      patient_id,
                'source':       source,
                'rep_id':       f'{patient_id}_r{i+1}',
            })
        except Exception as e:
            print(f'\n    Rep {i+1} skipped: {e}')
    print(f'{len(samples)} valid')
    return samples

# ── E. DATASET LOADERS ───────────────────────────────────

def _kps_from_df_rows(df, xyz_cols):
    return df[xyz_cols].values.astype(np.float32).reshape(len(df), N_JOINTS, 3)

def load_uiprmd():
    if not os.path.exists(UIPRMD_CSV):
        print(f'UI-PRMD not found: {UIPRMD_CSV}'); return []
    df = pd.read_csv(UIPRMD_CSV)
    xyz_cols = [f'{j}_{ax}' for j in JOINT_ORDER for ax in ['x','y','z']]
    samples  = []
    for (subj, mov, ex_id, lv), grp in df.groupby(['subject','movement','exercise_id','label']):
        grp = grp.sort_values('frame')
        raw = _kps_from_df_rows(grp, xyz_cols) / 1000.0
        try:
            kps = process_keypoints(raw)
            ex  = grp['exercise'].iloc[0]
            samples.append({'keypoints': kps, 'adj': ADJ,
                            'label': int(lv), 'quality': float(lv),
                            'exercise': ex,
                            'exercise_idx': EXERCISE2IDX.get(ex, EXERCISE2IDX['unknown']),
                            'subject': f'uiprmd_{subj}', 'source': 'uiprmd',
                            'scalars': extract_scalars(kps)})
        except Exception as e:
            print(f'  skip uiprmd {subj}/{mov}/{ex_id}: {e}')
    print(f'UI-PRMD: {len(samples)} samples')
    return samples

def load_kimore():
    if not os.path.exists(KIMORE_CSV):
        print(f'KIMORE not found: {KIMORE_CSV}'); return []
    df = pd.read_csv(KIMORE_CSV)
    xyz_cols = []
    for jn in ['HipLeft','KneeLeft','AnkleLeft','HipRight','KneeRight','AnkleRight']:
        xyz_cols += [f'{jn}_x', f'{jn}_y', f'{jn}_z']
    df['quality_norm'] = df[['cTS','cPO','cCF']].mean(axis=1) / 50.0
    samples = []
    for subj, grp in df.groupby('Subject'):
        grp = grp.sort_values('FrameID')
        raw = _kps_from_df_rows(grp, xyz_cols)
        try:
            kps = process_keypoints(raw)
            samples.append({'keypoints': kps, 'adj': ADJ,
                            'label': int(grp['label'].iloc[0]),
                            'quality': float(grp['quality_norm'].mean()),
                            'exercise': 'squat',
                            'exercise_idx': EXERCISE2IDX['squat'],
                            'subject': f'kimore_{subj}', 'source': 'kimore',
                            'scalars': extract_scalars(kps)})
        except Exception as e:
            print(f'  skip kimore {subj}: {e}')
    print(f'KIMORE: {len(samples)} samples')
    return samples

def load_keraal():
    if not os.path.exists(KERAAL_CSV):
        print(f'Keraal not found: {KERAAL_CSV}'); return []
    df = pd.read_csv(KERAAL_CSV)
    xyz_cols = []
    for jn in ['HipLeft','KneeLeft','AnkleLeft','HipRight','KneeRight','AnkleRight']:
        xyz_cols += [f'{jn}_x', f'{jn}_y', f'{jn}_z']
    samples = []
    for ann_key, grp in df.groupby('ann_key'):
        grp = grp.sort_values('FrameID') if 'FrameID' in grp.columns else grp
        raw = _kps_from_df_rows(grp, xyz_cols)
        try:
            kps  = process_keypoints(raw)
            subj = '-'.join(str(ann_key).split('-')[:3])
            samples.append({'keypoints': kps, 'adj': ADJ,
                            'label': int(grp['label'].iloc[0]),
                            'quality': float(grp['label'].iloc[0]),
                            'exercise': 'ctk_squat',
                            'exercise_idx': EXERCISE2IDX['ctk_squat'],
                            'subject': f'keraal_{subj}', 'source': 'keraal',
                            'scalars': extract_scalars(kps)})
        except Exception as e:
            print(f'  skip keraal {ann_key}: {e}')
    print(f'Keraal: {len(samples)} samples')
    return samples

def build_master_dataset():
    raw   = load_uiprmd() + load_kimore() + load_keraal()
    clean = []
    for s in raw:
        try:
            kps = safe_np(s['keypoints'], clip=5.0)
            sc  = safe_np(s.get('scalars', extract_scalars(kps)), clip=10.0)
            q   = float(np.nan_to_num(s.get('quality', s.get('label', 1)),
                                      nan=float(s.get('label', 1))))
            ex  = int(s.get('exercise_idx', EXERCISE2IDX['unknown']))
            if kps.shape != (TARGET_LEN, N_JOINTS, 3): raise ValueError('bad kps shape')
            if sc.shape  != (10,):                     raise ValueError('bad scalar shape')
            if not valid_np(kps) or not valid_np(sc):  raise ValueError('NaN/Inf')
            if not (0 <= ex < N_EXERCISES): ex = EXERCISE2IDX['unknown']
            s.update({'keypoints': kps, 'scalars': sc,
                      'label': int(s.get('label', 1)),
                      'quality': float(np.clip(q, 0, 1)),
                      'exercise_idx': ex})
            clean.append(s)
        except Exception as e:
            print(f"  DROP {s.get('subject','?')}: {e}")
    print(f'\nMaster dataset: {len(clean)} samples')
    return clean

def loso_split(samples, held_out):
    return ([s for s in samples if s['subject'] != held_out],
            [s for s in samples if s['subject'] == held_out])

def get_uiprmd_subjects(samples):
    return sorted({s['subject'] for s in samples if s['source'] == 'uiprmd'})

# ── F. MODEL ─────────────────────────────────────────────

class STGCNBlock(nn.Module):
    def __init__(self, c_in, c_out, ks=9, stride=1):
        super().__init__()
        self.gcn = nn.Linear(c_in, c_out)
        self.tcn = nn.Sequential(
            nn.BatchNorm2d(c_out), nn.ReLU(),
            nn.Conv2d(c_out, c_out, (ks,1), (stride,1), ((ks-1)//2, 0)),
            nn.BatchNorm2d(c_out), nn.Dropout(0.1),
        )
        self.res = (nn.Sequential(nn.Conv2d(c_in, c_out, 1, (stride,1)),
                                   nn.BatchNorm2d(c_out))
                    if c_in != c_out or stride != 1 else nn.Identity())
        self.relu = nn.ReLU()

    def forward(self, x, A):
        B, C, T, V = x.shape
        if A.dim() == 3: A = A[0]
        xs = x.permute(0,2,3,1).contiguous().view(B*T, V, C)
        xs = torch.bmm(A.unsqueeze(0).expand(B*T,-1,-1), xs)
        xs = self.gcn(xs).view(B, T, V, -1).permute(0,3,1,2)
        return self.relu(
            torch.nan_to_num(self.tcn(xs), 0.0) +
            torch.nan_to_num(self.res(x),  0.0)
        )

class STGCN(nn.Module):
    def __init__(self):
        super().__init__()
        self.input_norm = nn.LayerNorm(IN_CHANNELS * N_JOINTS)
        self.b1 = STGCNBlock(3, 32)
        self.b2 = STGCNBlock(32, 64)
        self.b3 = STGCNBlock(64, 128)

    def forward(self, x, A):
        B, C, T, V = x.shape
        x  = torch.clamp(x, -5.0, 5.0)
        xf = x.permute(0,2,1,3).contiguous().view(B*T, C*V)
        xf = self.input_norm(xf).view(B, T, C, V).permute(0,2,1,3)
        return self.b3(self.b2(self.b1(xf, A), A), A).mean(3).permute(0,2,1)

class ClinicalTransformer(nn.Module):
    def __init__(self, d=128, heads=4, d_ff=256, drop=0.1):
        super().__init__()
        pe  = torch.zeros(TARGET_LEN+1, d)
        pos = torch.arange(TARGET_LEN+1).unsqueeze(1).float()
        div = torch.exp(torch.arange(0,d,2).float() * (-np.log(10000.0)/d))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer('pe', pe.unsqueeze(0))
        self.cls  = nn.Parameter(torch.randn(1,1,d) * 0.02)
        self.drop = nn.Dropout(drop)
        mk = lambda: nn.TransformerEncoderLayer(d, heads, d_ff, drop,
                                                 batch_first=True, norm_first=True)
        self.l1, self.l2 = mk(), mk()
        self.n1, self.n2 = nn.LayerNorm(d), nn.LayerNorm(d)

    def forward(self, x, return_attn=False):
        B, T, _ = x.shape
        x = torch.cat([self.cls.expand(B,-1,-1), x], 1)
        x = self.drop(x + self.pe[:, :T+1, :])
        x = self.n1(self.l1(x))
        if return_attn:
            sa  = self.l2.self_attn
            xn  = self.l2.norm1(x)
            out, attn = sa(xn, xn, xn, need_weights=True, average_attn_weights=True)
            x2  = x + self.l2.dropout1(out)
            xn2 = self.l2.norm2(x2)
            ff  = self.l2.linear2(self.l2.dropout(self.l2.activation(self.l2.linear1(xn2))))
            return self.n2(x2 + self.l2.dropout2(ff))[:, 0, :], attn
        return self.n2(self.l2(x))[:, 0, :], None

class RehabNet(nn.Module):
    _N_MODES     = 2
    _N_EXERCISES = 10

    def __init__(self):
        super().__init__()
        self.stgcn       = STGCN()
        self.trans       = ClinicalTransformer()
        self.bilstm      = nn.LSTM(128, 64, num_layers=2, batch_first=True,
                                   bidirectional=True, dropout=0.1)
        self.bilstm_proj = nn.Sequential(
            nn.Linear(128, 128), nn.LayerNorm(128), nn.ReLU(), nn.Dropout(0.1))
        self.mode_emb    = nn.Embedding(self._N_MODES,      16)
        self.ex_emb      = nn.Embedding(self._N_EXERCISES,   8)
        self.shared      = nn.Sequential(
            nn.Linear(290, 128), nn.LayerNorm(128), nn.ReLU(), nn.Dropout(0.2))
        self.classify_head = nn.Linear(128, 2)
        self.quality_head  = nn.Linear(128, 1)
        self.ex_head       = nn.Linear(128, self._N_EXERCISES)
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None: nn.init.zeros_(m.bias)

    def encode(self, kps, adj, return_attn=False):
        if adj.dim() == 3: adj = adj[0]
        feats       = self.stgcn(kps, adj)
        cls, attn   = self.trans(feats, return_attn)
        lstm_out, _ = self.bilstm(feats)
        bilstm_ctx  = self.bilstm_proj(lstm_out.mean(1))
        return cls, bilstm_ctx, attn

    def forward(self, kps, adj, scalars, mode=None, exercise_idx=None):
        B, device = kps.shape[0], kps.device
        if mode         is None: mode         = torch.zeros(B, dtype=torch.long, device=device)
        if exercise_idx is None: exercise_idx = torch.zeros(B, dtype=torch.long, device=device)
        mode         = torch.clamp(mode,         0, self._N_MODES     - 1)
        exercise_idx = torch.clamp(exercise_idx, 0, self._N_EXERCISES - 1)
        cls, bilstm_ctx, _ = self.encode(kps, adj)
        x = self.shared(torch.cat([
            cls, bilstm_ctx, scalars,
            self.mode_emb(mode), self.ex_emb(exercise_idx),
        ], dim=1))
        return (self.classify_head(x),
                self.quality_head(x).squeeze(1),
                self.ex_head(cls))

    def predict_exercise(self, kps, adj):
        self.eval()
        with torch.no_grad():
            if adj.dim() == 3: adj = adj[0]
            cls, _, _ = self.encode(kps, adj)
            idx = int(self.ex_head(cls).argmax(1).item())
        return EXERCISE_LIST[idx], idx

# ── G. DATASET + DATALOADER ──────────────────────────────

class RehabDataset(Dataset):
    def __init__(self, samples, augment=False):
        self.samples = samples
        self.augment = augment

    def __len__(self): return len(self.samples)

    def __getitem__(self, idx):
        s   = self.samples[idx]
        kps = safe_np(s['keypoints'], clip=5.0)
        if self.augment: kps = self._aug(kps)
        return {
            'keypoints':    torch.from_numpy(safe_np(kps, clip=5.0)).permute(2,0,1).float(),
            'adj':          torch.from_numpy(ADJ).float(),
            'label':        torch.tensor(s['label'],        dtype=torch.long),
            'quality':      torch.tensor(s['quality'],      dtype=torch.float32),
            'scalars':      torch.from_numpy(safe_np(s['scalars'], clip=10.0)).float(),
            'exercise_idx': torch.tensor(s['exercise_idx'], dtype=torch.long),
            'exercise':     s['exercise'],
            'subject':      s['subject'],
        }

    def _aug(self, kps):
        kps = safe_np(kps, clip=5.0)
        if np.random.rand() < 0.5:
            n   = max(int(TARGET_LEN * np.random.uniform(0.8, 1.2)), MIN_FRAMES)
            tmp = np.zeros((n, N_JOINTS, 3), dtype=np.float32)
            for j in range(N_JOINTS):
                for c in range(3): tmp[:,j,c] = _resample(kps[:,j,c], n)
            kps = np.zeros((TARGET_LEN, N_JOINTS, 3), dtype=np.float32)
            for j in range(N_JOINTS):
                for c in range(3): kps[:,j,c] = _resample(tmp[:,j,c], TARGET_LEN)
        if np.random.rand() < 0.5:
            kps[:, [0,1,2,3,4,5], :] = kps[:, [3,4,5,0,1,2], :]
            kps[:, :, 0] *= -1.0
        if np.random.rand() < 0.5:
            kps += np.random.randn(*kps.shape).astype(np.float32) * 0.02
        if np.random.rand() < 0.3:
            th = np.radians(np.random.uniform(-10, 10))
            x, z = kps[:,:,0].copy(), kps[:,:,2].copy()
            kps[:,:,0] = np.cos(th)*x - np.sin(th)*z
            kps[:,:,2] = np.sin(th)*x + np.cos(th)*z
        return safe_np(kps, clip=5.0)

def collate(batch):
    return {
        k: torch.stack([b[k] for b in batch])
           if isinstance(batch[0][k], torch.Tensor)
           else [b[k] for b in batch]
        for k in batch[0]
    }

def build_loaders(train_samples, test_samples, batch_size=32):
    ex_counts = Counter(s['exercise'] for s in train_samples)
    total     = len(train_samples)
    weights   = [total / ex_counts[s['exercise']] for s in train_samples]
    sampler   = WeightedRandomSampler(weights, len(train_samples), replacement=True)
    return (
        DataLoader(RehabDataset(train_samples, augment=True),
                   batch_size=batch_size, sampler=sampler,
                   collate_fn=collate, num_workers=2),
        DataLoader(RehabDataset(test_samples, augment=False),
                   batch_size=batch_size, shuffle=False,
                   collate_fn=collate, num_workers=2),
    )

# ── H. TRAINING ──────────────────────────────────────────

def compute_class_weights(train_samples, device):
    n0 = sum(s['label']==0 for s in train_samples)
    n1 = sum(s['label']==1 for s in train_samples)
    tot = n0 + n1
    return torch.tensor([tot/(2*n0+EPS), tot/(2*n1+EPS)],
                        dtype=torch.float32, device=device)

def _train_epoch(model, loader, opt, device, cw, epoch=0):
    model.train()
    A = torch.from_numpy(ADJ).to(device)
    total, used, skipped = 0.0, 0, 0
    for b in loader:
        kps    = b['keypoints'].to(device)
        lbl    = b['label'].to(device)
        qual   = b['quality'].to(device)
        sc     = b['scalars'].to(device)
        ex_idx = b['exercise_idx'].to(device)
        good   = (torch.isfinite(kps).flatten(1).all(1) &
                  torch.isfinite(sc).all(1) & torch.isfinite(qual))
        if not good.all():
            kps,lbl,qual,sc,ex_idx = (t[good] for t in (kps,lbl,qual,sc,ex_idx))
        if kps.shape[0] == 0: skipped += 1; continue
        mode   = torch.zeros(kps.shape[0], dtype=torch.long, device=device)
        lg, qp, ex_lg = model(kps, A, sc, mode, ex_idx)
        if not (torch.isfinite(lg).all() and torch.isfinite(qp).all()):
            skipped += 1; continue
        loss = (F.cross_entropy(lg, lbl, weight=cw) +
                0.3 * F.mse_loss(torch.sigmoid(qp), torch.clamp(qual,0,1)) +
                0.5 * F.cross_entropy(ex_lg, ex_idx))
        if not torch.isfinite(loss): skipped += 1; continue
        opt.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        opt.step()
        total += loss.item(); used += 1
    if skipped: print(f'  ep{epoch}: skipped {skipped} batches')
    return total / max(used, 1)

@torch.no_grad()
def _evaluate(model, loader, device):
    model.eval()
    A = torch.from_numpy(ADJ).to(device)
    preds, labels, quals, qpreds = [], [], [], []
    for b in loader:
        kps    = b['keypoints'].to(device)
        sc     = b['scalars'].to(device)
        ex_idx = b['exercise_idx'].to(device)
        qual   = b['quality'].to(device)
        lbl    = b['label'].to(device)
        good   = (torch.isfinite(kps).flatten(1).all(1) & torch.isfinite(sc).all(1))
        if good.sum() == 0: continue
        kps,sc,ex_idx,qual,lbl = (t[good] for t in (kps,sc,ex_idx,qual,lbl))
        mode   = torch.zeros(kps.shape[0], dtype=torch.long, device=device)
        lg, qp, _ = model(kps, A, sc, mode, ex_idx)
        preds.extend(lg.argmax(1).cpu().numpy())
        labels.extend(lbl.cpu().numpy())
        quals.extend(qual.cpu().numpy())
        qpreds.extend(torch.sigmoid(qp).cpu().numpy())
    if not labels: return {'acc': 0.0, 'f1': 0.0, 'quality_r': 0.0}
    acc = accuracy_score(labels, preds)
    f1  = f1_score(labels, preds, average='macro', zero_division=0)
    r   = pearsonr(quals, qpreds)[0] if len(set(quals)) > 1 else 0.0
    print(classification_report(labels, preds,
          target_names=['incorrect','correct'], zero_division=0))
    print(f'  quality Pearson r={r:.3f}')
    return {'acc': acc, 'f1': f1, 'quality_r': r}

def run_loso(samples=None, n_epochs=N_EPOCHS, batch_size=32, lr=3e-4, patience=12):
    if samples is None: samples = build_master_dataset()
    device   = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    subjects = get_uiprmd_subjects(samples) or sorted({s['subject'] for s in samples})
    results, best_f1_overall, best_model = [], 0.0, None
    for subj in subjects:
        print(f"\n{'='*55}\nLOSO: {subj}\n{'='*55}")
        tr, te = loso_split(samples, subj)
        tl, vl = build_loaders(tr, te, batch_size)
        cw     = compute_class_weights(tr, device)
        model  = RehabNet().to(device)
        opt    = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
        def lr_fn(ep):
            w = 5
            if ep < w: return (ep+1)/w
            return 0.5*(1+np.cos(np.pi*(ep-w)/max(n_epochs-w,1)))
        sch = torch.optim.lr_scheduler.LambdaLR(opt, lr_fn)
        best_f1, best_state, no_imp = 0.0, None, 0
        for ep in range(n_epochs):
            loss = _train_epoch(model, tl, opt, device, cw, epoch=ep)
            sch.step()
            if (ep+1) % 5 == 0:
                model.eval()
                pl, ll = [], []
                with torch.no_grad():
                    A2 = torch.from_numpy(ADJ).to(device)
                    for b in vl:
                        kps    = b['keypoints'].to(device)
                        sc     = b['scalars'].to(device)
                        ex_idx = b['exercise_idx'].to(device)
                        lbl    = b['label']
                        good   = (torch.isfinite(kps).flatten(1).all(1) &
                                  torch.isfinite(sc).all(1))
                        if good.sum() == 0: continue
                        kps,sc,ex_idx = kps[good],sc[good],ex_idx[good]
                        lbl  = lbl[good.cpu()]
                        mode = torch.zeros(kps.shape[0], dtype=torch.long, device=device)
                        lg, _, _ = model(kps, A2, sc, mode, ex_idx)
                        pl.extend(lg.argmax(1).cpu().numpy())
                        ll.extend(lbl.numpy())
                model.train()
                vf1 = f1_score(ll, pl, average='macro', zero_division=0)
                print(f'  ep{ep+1:3d} loss={loss:.4f}  lr={sch.get_last_lr()[0]:.2e}  val_f1={vf1:.3f}')
                if vf1 > best_f1:
                    best_f1 = vf1
                    best_state = copy.deepcopy(model.state_dict())
                    no_imp = 0
                else:
                    no_imp += 1
                    if no_imp >= patience: print(f'  Early stop ep{ep+1}'); break
        if best_state: model.load_state_dict(best_state)
        if best_f1 > best_f1_overall:
            best_f1_overall = best_f1
            best_model = copy.deepcopy(model.state_dict())
        print(f'\n── Eval: {subj} ──')
        results.append(_evaluate(model, vl, device))
    if best_model:
        os.makedirs(os.path.dirname(MODEL_SAVE), exist_ok=True)
        torch.save(best_model, MODEL_SAVE)
        print(f'\nBest model → {MODEL_SAVE}')
    accs = [r['acc'] for r in results]
    f1s  = [r['f1']  for r in results]
    print(f"\n{'='*55}\nLOSO RESULTS\n"
          f"  Acc={np.mean(accs):.3f}±{np.std(accs):.3f}\n"
          f"  F1 ={np.mean(f1s):.3f}±{np.std(f1s):.3f}\n{'='*55}")
    final = RehabNet().to(device)
    if best_model: final.load_state_dict(best_model)
    return results, final

# ── I. INFERENCE + FEEDBACK ──────────────────────────────

def compute_torque(quality, mode):
    m = HARDWARE_MODES.get(mode, HARDWARE_MODES[0])
    return float(np.clip(m['scale']*quality + m['bias'], m['min'], m['max']))

def generate_feedback(label, quality, scalars):
    s = np.asarray(scalars)
    triggered = sorted([r for r in FEEDBACK_RULES if r['check'](s)],
                       key=lambda r: r['priority'], reverse=True)
    flags = [r['name'] for r in triggered]
    if label == 1 and quality >= 0.75:
        return {'message':'Great rep — keep it up!','short':'Great rep',
                'flags':[],'severity':'good'}
    if label == 1 and quality >= 0.5:
        return {'message':'Good rep — maintain that form.','short':'Good rep',
                'flags':flags,'severity':'good'}
    if triggered:
        top = triggered[0]
        return {'message':top['message'],'short':top['short'],
                'flags':flags,'severity':'error' if top['priority']>=8 else 'warning'}
    return {'message':'Focus on smooth, controlled movement.',
            'short':'Keep it smooth','flags':[],'severity':'warning'}

def build_hardware_payload(sample, quality, scalars, torque, mode):
    kps = sample['keypoints']
    def _ang(a, b, c):
        ba, bc = a-b, c-b
        d = np.linalg.norm(ba, axis=1)*np.linalg.norm(bc, axis=1) + EPS
        return np.degrees(np.arccos(np.clip(np.sum(ba*bc, axis=1)/d, -1, 1)))
    lk = _ang(kps[:,0,:], kps[:,1,:], kps[:,2,:])
    rk = _ang(kps[:,3,:], kps[:,4,:], kps[:,5,:])
    l_peak = float(np.min(lk)); r_peak = float(np.min(rk))
    l_rom  = float(np.max(lk)-l_peak); r_rom = float(np.max(rk)-r_peak)
    ex     = sample.get('exercise','unknown')
    target = TARGET_ANGLES.get(ex, TARGET_ANGLES['default'])
    l_def  = max(0., target-l_peak); r_def = max(0., target-r_peak)
    return {
        'torque': round(torque,4), 'mode': HARDWARE_MODES[mode]['name'],
        'mode_int': mode,
        'joint': {'left_knee_peak_deg': round(l_peak,2),
                  'right_knee_peak_deg': round(r_peak,2),
                  'left_knee_rom_deg': round(l_rom,2),
                  'right_knee_rom_deg': round(r_rom,2)},
        'target': {'knee_target_deg': target,
                   'left_deficit_deg': round(l_def,2),
                   'right_deficit_deg': round(r_def,2)},
        'torque_per_degree': round(torque/max(l_def,1.0), 5),
    }

@torch.no_grad()
def infer_sample(model, sample, device=DEVICE, hardware_mode=0, debug=False):
    model.eval()
    kps_t  = torch.from_numpy(sample['keypoints']).permute(2,0,1).unsqueeze(0).to(device)
    adj_t  = torch.from_numpy(ADJ).to(device)
    # FIX: apply distribution alignment before feeding to model
    aligned_sc = align_scalars(sample['scalars'])
    sc_t   = torch.from_numpy(aligned_sc).unsqueeze(0).to(device)
    mode_t = torch.tensor([hardware_mode], dtype=torch.long, device=device)
    ex_t   = torch.tensor([sample['exercise_idx']], dtype=torch.long, device=device)

    if debug:
        sc_raw = sample['scalars']
        names  = ['l_rom','r_rom','l_peak','r_peak','sym','vel','jerk','trunk','lag','smooth']
        scales = [180,180,180,180,100,200,10,1,150,1]
        mp_std_safe = np.where(MP_STD < 1e-6, 1.0, MP_STD)
        z_scores = (sc_raw - MP_MEAN) / mp_std_safe if SCALAR_ALIGN else np.zeros(10)
        print(f'    Scalar debug [{sample.get("rep_id","?")}]  '
              f'(align={"ON" if SCALAR_ALIGN else "OFF"}):')
        for i, n in enumerate(names):
            z_warn = f'  ⚠ z={z_scores[i]:.1f}!' if abs(z_scores[i]) > 3 else ''
            print(f'      {n:10s}  raw={sc_raw[i]:.4f}  '
                  f'phys={sc_raw[i]*scales[i]:.2f}  '
                  f'aligned={aligned_sc[i]:.4f}{z_warn}')

    logits, quality, *_ = model(kps_t, adj_t, sc_t, mode_t, ex_t)
    label   = int(logits.argmax(1).item())
    quality = float(torch.sigmoid(quality).item())

    # NOTE: no rule-based override — trust the model.
    # An override that fires on quality < 0.4 (most reps) and uses a
    # trivially-low ROM threshold (>25°) will force label=1 on almost
    # every rep, producing the 5/5 CORRECT artefact seen in testing.
    # If classification is still wrong after scalar alignment is verified,
    # the fix is fine-tuning on MediaPipe data, not a hardcoded rule.

    sc_raw = sample['scalars']
    torque = compute_torque(quality, hardware_mode)
    fb     = generate_feedback(label, quality, sc_raw)
    hw     = build_hardware_payload(sample, quality, sc_raw, torque, hardware_mode)

    return {
        'rep_id':         sample.get('rep_id','?'),
        'exercise':       sample.get('exercise','unknown'),
        'label':          label,
        'correct':        label == 1,
        'quality_score':  round(quality, 4),
        'feedback':       fb['message'],
        'feedback_short': fb['short'],
        'severity':       fb['severity'],
        'flags':          fb['flags'],
        'hardware':       hw,
        'torque_signal':  torque,
        'mode_name':      HARDWARE_MODES[hardware_mode]['name'],
        'scalars':        sc_raw.tolist(),
        'scalars_aligned': aligned_sc.tolist(),
    }

def _predict_exercise_from_samples(model, samples, device=DEVICE):
    if not samples: return 'unknown', EXERCISE2IDX['unknown']
    votes, adj_t = [], torch.from_numpy(ADJ).to(device)
    model.eval()
    with torch.no_grad():
        for s in samples:
            kps_t = torch.from_numpy(s['keypoints']).permute(2,0,1).unsqueeze(0).to(device)
            pred_ex, pred_idx = model.predict_exercise(kps_t, adj_t)
            votes.append(pred_ex)
    counts  = Counter(votes)
    pred_ex = counts.most_common(1)[0][0]
    print(f'[Exercise Classification] Votes: {dict(counts)}')
    return pred_ex, EXERCISE2IDX.get(pred_ex, EXERCISE2IDX['unknown'])

# ── J. PATIENT SESSION ───────────────────────────────────

def run_patient_video(video_path, patient_id,
                      model=None, exercise=None,
                      hardware_mode=0, device=DEVICE, debug=True):
    print(f"\n{'='*50}\nPatient: {patient_id}\n{'='*50}")
    active_exercise = exercise or 'unknown'

    print('\n[PS1] Processing video...')
    df      = ps1_process_video(video_path, patient_id, active_exercise)
    fps_vid = df.attrs.get('fps', 30.0)

    if debug and 'angle_knee_L_smooth' in df.columns:
        import matplotlib.pyplot as plt
        a_l = df['angle_knee_L_smooth'].values
        a_r = df['angle_knee_R_smooth'].values
        print(f'  Angle L: min={a_l.min():.1f}° max={a_l.max():.1f}° '
              f'ROM={a_l.max()-a_l.min():.1f}°')
        print(f'  Angle R: min={a_r.min():.1f}° max={a_r.max():.1f}° '
              f'ROM={a_r.max()-a_r.min():.1f}°')
        plt.figure(figsize=(13,3))
        plt.plot(a_l, color='steelblue', label='Left knee')
        plt.plot(a_r, color='coral', alpha=0.7, label='Right knee')
        plt.axhline(90, color='green', linestyle='--', alpha=0.5, label='90° target')
        plt.xlabel('Frame'); plt.ylabel('Angle (°)')
        plt.title(f'Knee angles — {patient_id}  fps={fps_vid:.0f}')
        plt.legend(); plt.tight_layout(); plt.show()

    print('\n[Bridge] Segmenting reps...')

    if exercise is None and model is not None:
        rough = ps1_df_to_samples(df, patient_id, 'unknown')
        if not rough:
            print('No valid rough reps found'); return {}
        pred_ex, pred_idx = _predict_exercise_from_samples(model, rough, device)
        active_exercise   = pred_ex
        print(f'\n[Exercise] Predicted: {active_exercise}')
        samples = ps1_df_to_samples(df, patient_id, active_exercise)
        for s in samples:
            s['exercise'] = active_exercise; s['exercise_idx'] = pred_idx
    else:
        print(f'\n[Exercise] Using: {active_exercise}')
        samples = ps1_df_to_samples(df, patient_id, active_exercise)

    if not samples:
        print('No valid reps found — check video quality'); return {}

    if model is None:
        return {'patient': patient_id, 'exercise': active_exercise,
                'n_reps': len(samples), 'ps1_only': True, 'samples': samples}

    print('\n[PS2] Running RehabNet inference...')
    results = []
    for s in samples:
        out    = infer_sample(model, s, device, hardware_mode, debug=debug)
        status = 'CORRECT ✓' if out['label'] == 1 else 'INCORRECT ✗'
        print(f"  {out['rep_id']:20s} | {status} "
              f"| quality={out['quality_score']:.2f} "
              f"| torque={out['torque_signal']:.2f} "
              f"| {out['feedback_short']}")
        results.append(out)

    n_correct = sum(r['label']==1 for r in results)
    avg_q     = float(np.mean([r['quality_score'] for r in results]))
    summary   = {
        'patient':     patient_id,
        'exercise':    active_exercise,
        'fps':         fps_vid,
        'n_reps':      len(results),
        'n_correct':   n_correct,
        'pct_correct': round(n_correct/max(len(results),1)*100, 1),
        'avg_quality': round(avg_q, 3),
        'avg_torque':  round(float(np.mean([r['torque_signal'] for r in results])),3),
        'hw_mode':     HARDWARE_MODES[hardware_mode]['name'],
        'reps':        results,
    }
    print(f'\nSession complete: {len(results)} reps  '
          f'correct={n_correct}/{len(results)}  avg_quality={avg_q:.3f}')
    return summary


print('All functions loaded. ✓')
print(f'RehabNet._N_EXERCISES={RehabNet._N_EXERCISES}  '
      f'N_EXERCISES={N_EXERCISES}  '
      f'{"✓ MATCH" if RehabNet._N_EXERCISES == N_EXERCISES else "✗ MISMATCH"}')

OLD_EXERCISE_LIST = [
    'deep_squat', 'hurdle_step', 'inline_lunge', 'side_lunge',
    'sit_to_stand', 'straight_leg_raise',
    'squat', 'ctk_squat', 'unknown'
]

def adapt_exercise_weights(state, old_list, new_list):
    old_n, new_n = len(old_list), len(new_list)
    if old_n == new_n: return state
    print(f'Adapting exercise heads: {old_n} → {new_n}')
    for key_w, key_b in [('ex_emb.weight', None), ('ex_head.weight', 'ex_head.bias')]:
        if key_w in state:
            old_w = state[key_w]
            new_w = torch.randn(new_n, old_w.shape[1]) * 0.02
            for old_i, name in enumerate(old_list):
                if name in new_list: new_w[new_list.index(name)] = old_w[old_i]
            state[key_w] = new_w
        if key_b and key_b in state:
            old_b = state[key_b]
            new_b = torch.zeros(new_n)
            for old_i, name in enumerate(old_list):
                if name in new_list: new_b[new_list.index(name)] = old_b[old_i]
            state[key_b] = new_b
    return state

model = RehabNet().to(DEVICE)
state = torch.load('/content/drive/MyDrive/models/rehabnet_best.pth', map_location=DEVICE)
if isinstance(state, dict) and 'model_state_dict' in state:
    state = state['model_state_dict']
state = adapt_exercise_weights(state, OLD_EXERCISE_LIST, EXERCISE_LIST)
model.load_state_dict(state, strict=True)
model.eval()
print('Model loaded ✓')

try:
    import serial
    SERIAL_AVAILABLE = True
except ImportError:
    SERIAL_AVAILABLE = False
    print('pyserial not installed — stub mode')

import json

HW_PORT    = None    # set to '/dev/ttyUSB0' or 'COM3' when hardware ready
HW_BAUD    = 115200
HW_ENABLED = False
_hw_serial = None

def hw_connect(port=HW_PORT, baud=HW_BAUD):
    global _hw_serial, HW_ENABLED
    if port is None or not SERIAL_AVAILABLE:
        print('Hardware: stub mode (set HW_PORT when ready)'); return
    try:
        _hw_serial = serial.Serial(port, baud, timeout=1)
        HW_ENABLED = True
        print(f'Hardware connected: {port} @ {baud}')
    except Exception as e:
        print(f'Hardware connect failed: {e} — stub mode')

def hw_send(hw_payload: dict, rep_id: str = ''):
    cmd = {
        'rep':            rep_id,
        'torque':         hw_payload['torque'],
        'mode':           hw_payload['mode_int'],
        'l_peak_deg':     hw_payload['joint']['left_knee_peak_deg'],
        'r_peak_deg':     hw_payload['joint']['right_knee_peak_deg'],
        'target_deg':     hw_payload['target']['knee_target_deg'],
        'l_deficit':      hw_payload['target']['left_deficit_deg'],
        'r_deficit':      hw_payload['target']['right_deficit_deg'],
        'torque_per_deg': hw_payload['torque_per_degree'],
    }
    msg = json.dumps(cmd) + '\n'
    if HW_ENABLED and _hw_serial and _hw_serial.is_open:
        try:
            _hw_serial.write(msg.encode('utf-8')); return
        except Exception as e:
            print(f'  HW send error: {e}')
    print(f'  [HW STUB] torque={cmd["torque"]:.3f}  mode={cmd["mode"]}  '
          f'target={cmd["target_deg"]}°  L_deficit={cmd["l_deficit"]}°  '
          f'R_deficit={cmd["r_deficit"]}°')

def hw_disconnect():
    global _hw_serial, HW_ENABLED
    if _hw_serial and _hw_serial.is_open:
        _hw_serial.close(); HW_ENABLED = False
        print('Hardware disconnected')

hw_connect()

from google.colab import files
import os, time

print('Select your video file...')
uploaded  = files.upload()
clip_path = os.path.abspath(list(uploaded.keys())[0])
print(f'clip_path = {clip_path}')
print(f'size:     {os.path.getsize(clip_path)/1e6:.2f} MB')

summary = run_patient_video(
    video_path    = clip_path,
    patient_id    = 'P001',
    model         = model,
    exercise      = 'squat',  # change to match your video
    hardware_mode = 0,
    device        = DEVICE,
    debug         = True,
)

print('\nPer-rep breakdown + hardware commands:')
for rep in summary.get('reps', []):
    hw_send(rep['hardware'], rep_id=rep['rep_id'])
    print(f"  {rep['rep_id']:20s} {'✓' if rep['correct'] else '✗'}"
          f"  q={rep['quality_score']:.2f}  \"{rep['feedback']}\"")

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

CLIP_SECONDS  = 15
LIVE_CLIP     = '/content/live_clip.webm'
PATIENT_ID    = 'P001'
EXERCISE      = 'inline_lunge'   # set explicitly — auto-classify unreliable until fine-tuned
HARDWARE_MODE = 0                # 0=assist, 1=resist

def record_video(filename=LIVE_CLIP, seconds=CLIP_SECONDS):
    js = Javascript(f'''
    async function recordVideo() {{
      const div = document.createElement('div');
      const video = document.createElement('video');
      video.style.display = 'block'; video.width = 480;
      video.muted = true; video.autoplay = true;
      div.appendChild(video); document.body.appendChild(div);
      const stream = await navigator.mediaDevices.getUserMedia({{video:true,audio:false}});
      video.srcObject = stream; await video.play();
      const recorder = new MediaRecorder(stream, {{mimeType:'video/webm'}});
      const chunks = [];
      recorder.ondataavailable = e => chunks.push(e.data);
      const statusDiv = document.createElement('div');
      statusDiv.style.fontSize = '20px'; statusDiv.style.fontWeight = 'bold';
      div.appendChild(statusDiv);
      recorder.start();
      for (let t = {seconds}; t > 0; t--) {{
        statusDiv.innerText = `Recording... ${{t}}s remaining`;
        await new Promise(r => setTimeout(r, 1000));
      }}
      recorder.stop(); await new Promise(r => recorder.onstop = r);
      stream.getTracks().forEach(t => t.stop()); div.remove();
      const blob = new Blob(chunks, {{type:'video/webm'}});
      const buffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(buffer);
      let binary = '';
      for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
      return btoa(binary);
    }}
    ''')
    display(js)
    print(f'Allow camera access. Recording for {seconds}s...')
    data   = eval_js('recordVideo()')
    binary = b64decode(data)
    with open(filename, 'wb') as f:
        f.write(binary)
    print(f'Saved: {filename}  ({len(binary)/1024:.1f} KB)')
    return filename

# ── Record and process ───────────────────────────────────
clip_path = record_video(LIVE_CLIP, CLIP_SECONDS)

summary = run_patient_video(
    video_path    = clip_path,
    patient_id    = PATIENT_ID,
    model         = model,
    exercise      = EXERCISE,
    hardware_mode = HARDWARE_MODE,
    device        = DEVICE,
    debug         = True,
)

print('\nPer-rep breakdown + hardware commands:')
for rep in summary.get('reps', []):
    hw_send(rep['hardware'], rep_id=rep['rep_id'])
    print(f"  {rep['rep_id']:20s} {'✓' if rep['correct'] else '✗'}"
          f"  q={rep['quality_score']:.2f}  \"{rep['feedback']}\"")

from google.colab import files
import os, time

print('Select your video file...')
uploaded  = files.upload()
clip_path = os.path.abspath(list(uploaded.keys())[0])
print(f'clip_path = {clip_path}')
print(f'size:     {os.path.getsize(clip_path)/1e6:.2f} MB')

summary = run_patient_video(
    video_path    = clip_path,
    patient_id    = 'P001',
    model         = model,
    exercise      = 'squat',  # change to match your video
    hardware_mode = 0,
    device        = DEVICE,
    debug         = True,
)

print('\nPer-rep breakdown + hardware commands:')
for rep in summary.get('reps', []):
    hw_send(rep['hardware'], rep_id=rep['rep_id'])
    print(f"  {rep['rep_id']:20s} {'✓' if rep['correct'] else '✗'}"
          f"  q={rep['quality_score']:.2f}  \"{rep['feedback']}\"")